[build]
  publish = "dist/spa"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/reviews"
  to = "/.netlify/functions/getReviews"
  status = 200

[[redirects]]
  from = "/api/addReview"
  to = "/.netlify/functions/addReview"
  status = 200
